{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-prac.fullname" . }}-mongodb
  labels:
    {{- include "k8s-prac.labels" . | nindent 4 }}
    component: mongodb
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: mongodb
      protocol: TCP
      name: mongodb
  selector:
    {{- include "k8s-prac.selectorLabels" . | nindent 4 }}
    component: mongodb
{{- end }}
